### ISSUE TITLE
does not work unless activated by python3

### ISSUE THREAD

**Issue by mattraimondi** [Fitzgibbons/Mac-SSH-Proxy#1]
when simply typing "proxy" nothing happens
when typing "proxy"  with any argument the output is always: "direct://"

only when prefixing python3 like "python3 /usr/local/bin/proxy"  does the program work as intended.

my computer: MacBook Pro 2017, OS X 10.13.3

++

tested on an iMac mid-2011, OS X 10.13.3, and it works on that

**Comment by Fitzgibbons** [comment]
Does the first line of your proxy file have a valid reference to your python3 executable? Such as:
`#! /usr/local/bin/python3`

**Comment by mattraimondi** [comment]
Yes. It was working fine up until recently.

**Comment by Fitzgibbons** [comment]
Does the help message not even print?

**Comment by mattraimondi** [comment]
No, the program just hangs.

**Comment by Fitzgibbons** [comment]
Then the program must not be running properly and either your file reference is wrong, your python reference is wrong, or proxy is pointing somewhere else. If the program runs with no parameters it would always print the help message. If you would like to test that this is the problem, comment out the first try except clause (and the subprocess import). If it still hangs, one of those references is not correct.

**Comment by mattraimondi** [comment]
I'm such an idiot! Apparently, MacPorts had installed another program with the same name to /opt/local/bin/proxy and I wasn't able to see it there until I renamed the one in /usr/local/bin to another name. Thanks for the help!
